steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/custom-maven-java24', '-f', 'Dockerfile.maven', '.']

  - name: 'gcr.io/$PROJECT_ID/custom-maven-java24'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/elixirline-backend', '.']

images:
  - 'gcr.io/$PROJECT_ID/elixirline-backend'
