steps:
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/elixirline_backend', '.']
    dir: '.'

images:
  - 'gcr.io/$PROJECT_ID/elixirline_backend'
