server:
  port: ${PORT:8080}
  forward-headers-strategy: native
spring:
  config:
    import: "optional:env.properties"
  application:
    name: elixirline_backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    days: ${JWT_DAYS}

firebase:
  credentials: ${FIREBASE_CREDENTIALS}

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME}

web3:
  network:
    url: ${WEB3_NETWORK_URL}
  contract:
    address: ${WEB3_CONTRACT_ADDRESS}
  wallet:
    address: ${WALLET_ADDRESS}
  private:
    key: ${WEB3_PRIVATE_KEY}
  gas:
    limit: ${WEB3_GAS_LIMIT}
    price: ${WEB3_GAS_PRICE}


logging:
  level:
    root: INFO
    org.we3j: DEBUG
    com.elixirline: DEBUG

google:
  maps:
    api-key: ${GOOGLE_MAP_KEY}

#  cloud:
#    azure:
#      storage:
#        account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
#        account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
#
#  servlet:
#    multipart:
#      max-file-size: 2MB
#      max-request-size: 20MB