server:
  port: ${SERVER_PORT}
spring:
  config:
    import:
      - env.properties
  application:
    name: elixirline_backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

#  cloud:
#    azure:
#      storage:
#        account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
#        account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
#
#  servlet:
#    multipart:
#      max-file-size: 2MB
#      max-request-size: 20MB

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    days: ${JWT_DAYS}

firebase:
  credentials: ${FIREBASE_CREDENTIALS}

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME}